server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod_user_db
    username: useradmin
    password: uadmin123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect